### ISSUE TITLE
Randomized MAIN.SFX

### ISSUE THREAD

**Issue by BlazinDevilify** [DanzaG/TR2-Rando#111] opened 2021-03-04 23:04 UTC
My idea is to change the order of samples inside the MAIN.SFX file, so that the sound effects are reassigned randomly.

**Comment by BlazinDevilify** [comment] 2021-03-04 23:04
I made a simple tool to read the wave samples from the MAIN.SFX file and I attempted to integrate it into the existing framework but I have trouble getting my sound swapper working. I noticed that the MAIN.SFX is not copied into the wip folder but I don't know where to change that.

**Comment by lahm86** [comment] 2021-03-05 07:16
TRGE handles what gets backed up and copied to the WIP and target folders, so this would need to updated if the sfx file was to be included.

Alternatively, you could modify the SampleIndices array in TR2Level as I believe this holds the list of pointers into the sfx file. That would probably give better performance as it would keep the modifications in the level files only and would avoid the IO that would be involved in the large sfx file. 

https://opentomb.github.io/TRosettaStone3/trosettastone.html#_sample_indices

**Comment by BlazinDevilify** [comment] 2021-03-05 19:59
@lahm86 I tried changing the indices but when I do that the game crashes. Perhaps the game doesn't like it if I mix up the order completely. Maybe there's some detail I'm overseeing...

**Comment by lahm86** [comment] 2021-03-06 12:39
That's a shame, @BlazinDevilify. I will try to get some time this weekend to see if I can find out any more. Perhaps changing the sample value in tr_sound_details could work, as that points into SampleIndices. The crash is maybe caused by the unused indices in SampleIndices, but I'll do some testing to see what I can find.

**Comment by lahm86** [comment] 2021-03-09 22:02
The following results in a _very_ surreal output.
```
TR2Level lvl = new TR2LevelReader().ReadLevel("boat.tr2");
Random rand = new Random();
foreach (TRSoundDetails sound in lvl.SoundDetails)
{
    sound.Sample = lvl.SoundDetails[rand.Next(0, lvl.SoundDetails.Length)].Sample;
}
new TR2LevelWriter().WriteLevelToFile(lvl, "boat.tr2");
```
I don't know if this is the type of effect you'd be looking for. It might be better IMO to be more subtle and to target only specific sounds like maybe footsteps, or weapons firing. For that, I think there would need to be a lookup table of sorts for what the `SampleIndices`' values point to in MAIN.SFX. I'm guessing you have already been able to split that file into the individual WAV tracks? You could group certain indices together, such as potential `FootStepIndices`, or potential `GunshotIndices`. You could then iterate over each `TRSoundDetails` for the level, find which group the value of its `Sample` index is in (if any), and pick a different index from that group to use instead.

Just to clarify, `TRSoundDetails.Sample` stores the index into `SampleIndices` and the value at that index points to the track in MAIN.SFX.

Randomizing trigger music - such as Venice Violins playing when Lara turns on the stereo in HSH - I believe will rely on FloorData being available to manipulate (#110) - see 4.6.9 in [TRosettaStone3](https://opentomb.github.io/TRosettaStone3/trosettastone.html#trigger_actions).

**Comment by BlazinDevilify** [comment] 2021-03-10 09:10
@lahm86 Yeah great point, I could do that. Thanks for looking into it!

**Comment by lahm86** [comment] 2021-04-13 14:53
> @lahm86 I tried changing the indices but when I do that the game crashes. Perhaps the game doesn't like it if I mix up the order completely. Maybe there's some detail I'm overseeing...

@BlazinDevilify  I've been working on #97 and have discovered that the values in SampleIndices have to remain in numerical ascending order. This is of course a real pain when trying to add enemy sounds as it means everything else "above" the sample index has to be shifted, and so anything that points to those indices needs to be changed. Just thought I'd mention it - it could be why you were seeing crashes before. For me, the game was just closing with no error message when I tried to start a level I'd modified.

**Comment by BlazinDevilify** [comment] 2021-04-13 17:07
> > @lahm86 I tried changing the indices but when I do that the game crashes. Perhaps the game doesn't like it if I mix up the order completely. Maybe there's some detail I'm overseeing...
> 
> @BlazinDevilify I've been working on #97 and have discovered that the values in SampleIndices have to remain in numerical ascending order. This is of course a real pain when trying to add enemy sounds as it means everything else "above" the sample index has to be shifted, and so anything that points to those indices needs to be changed. Just thought I'd mention it - it could be why you were seeing crashes before. For me, the game was just closing with no error message when I tried to start a level I'd modified.

Ahhh, that makes sense. I gotta get back into it when I have some time. I'm curious if I can use samples that are normally not used in the level, I'll try to find out

**Comment by lahm86** [comment] 2021-04-13 20:11
Yeah, it should work. I have some non-native enemies ported now to other levels, including their sounds. The way I did it was to append all the "new" indices into SampleIndices, make a temporary cache of the indices, sort the indices, and then remap what each TRSoundDetails.Sample points to. Fortunately it's only TRSoundDetails that use the indices.
```C#
// Store the values from SampleIndices against their current positions in the list.
List<uint> sampleIndices = Level.SampleIndices.ToList();
Dictionary<int, uint> indexMap = new Dictionary<int, uint>();
for (int i = 0; i < sampleIndices.Count; i++)
{
    indexMap[i] = sampleIndices[i];
}

// Sort the indices to avoid the game crashing
sampleIndices.Sort();

// Remap each SoundDetail to use the new index of the sample it points to
foreach (TRSoundDetails soundDetails in Level.SoundDetails)
{
    soundDetails.Sample = (ushort)sampleIndices.IndexOf(indexMap[soundDetails.Sample]);
}

// Save the samples back to the level
Level.SampleIndices = sampleIndices.ToArray();
```

**Closed** 2021-11-20 13:05 UTC
